# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 07:43
from __future__ import unicode_literals

import cropdetection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropdetection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='band',
            field=models.FileField(help_text='Select band file(.tif).', max_length=300, upload_to=cropdetection.models.band_upload_dir),
        ),
    ]
