# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 12:39
from __future__ import unicode_literals

import cropdetection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropdetection', '0002_auto_20180115_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyze',
            name='result_s1',
        ),
        migrations.RemoveField(
            model_name='analyze',
            name='result_s2',
        ),
        migrations.AddField(
            model_name='analyze',
            name='result',
            field=models.FileField(blank=True, help_text='Select the result file(.tif).', upload_to=cropdetection.models.analyze_upload_dir),
        ),
    ]
