# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cropdetection', '0004_auto_20180116_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyze',
            name='last_modified_date',
        ),
        migrations.RemoveField(
            model_name='analyze',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='analyze',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
