# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropdetection', '0007_auto_20180117_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyze',
            name='date',
            field=models.DateField(),
        ),
    ]
