# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 09:31
from __future__ import unicode_literals

import cropdetection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropdetection', '0009_band_input_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='input_path',
        ),
        migrations.AddField(
            model_name='analyze',
            name='input_path',
            field=models.FileField(default='', help_text='Select input path file directory.', max_length=300, upload_to=cropdetection.models.band_upload_dir),
            preserve_default=False,
        ),
    ]
