# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 09:50
from __future__ import unicode_literals

import cropdetection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropdetection', '0010_auto_20180121_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyze',
            name='input_path',
            field=models.FileField(blank=True, help_text='Select input path file directory.', max_length=300, upload_to=cropdetection.models.band_upload_dir),
        ),
    ]
