# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 08:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cropdetection', '0013_auto_20180129_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyze',
            name='color_map',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
