# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 07:32
from __future__ import unicode_literals

import cropdetection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropdetection', '0014_analyze_color_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyze',
            name='result',
            field=models.FileField(blank=True, help_text='Select the result file(.tif).', max_length=300, null=True, upload_to=cropdetection.models.analyze_upload_dir),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='comment',
            field=models.TextField(blank=True, help_text='any more comment?', max_length=1000, null=True),
        ),
    ]
