# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 10:16
from __future__ import unicode_literals

import cropdetection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropdetection', '0015_auto_20180207_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyze',
            name='result_image_1',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to=cropdetection.models.analyze_upload_dir),
        ),
        migrations.AddField(
            model_name='analyze',
            name='result_image_2',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to=cropdetection.models.analyze_upload_dir),
        ),
    ]
